name: Daily Mandi Scraper

on:
  schedule:
    - cron: '0 4 * * *'   # Runs daily at 4 AM UTC (9:30 AM IST)
    - cron: '0 12 * * *'  # Runs daily at 12 PM UTC (5:30 PM IST)
  workflow_dispatch:      # Allow manual trigger from GitHub UI

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          pip install requests beautifulsoup4 firebase-admin

      - name: Run scraper
        env:
          FIREBASE_CREDENTIALS_JSON: ${{ secrets.FIREBASE_CREDENTIALS_JSON }}
        run: |
          python mandi_scraper.py
