name: Daily Mandi Scraper

on:
  schedule:
    - cron: '0 4 * * *'
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests beautifulsoup4 firebase-admin

    - name: Set up Firebase credentials
      env:
        FIREBASE_JSON: ${{ secrets.FIREBASE_JSON }}
      run: |
        echo "$FIREBASE_JSON" > authenticationapp-c3711-firebase-adminsdk-fbsvc-f96d0b7bf3.json

    - name: Run mandi_scraper.py
      run: |
        python mandi_scraper.py
